version: '3.3'
services:
  db:
    image: mariadb:10.3
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      #- /home/ubuntu/passbolt/mariadb:/var/lib/mysql
      - /mnt/docker/passbolt/mariadb:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - db
    environment:
    #APP_FULL_BASE_URL: http://passbolt.storvix.eu
      APP_FULL_BASE_URL: http://192.168.10.121:8099
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
      EMAIL_DEFAULT_FROM_NAME: "Passbolt"
      EMAIL_DEFAULT_FROM: "passbolt@docker-vm1.storvix.eu"
      EMAIL_TRANSPORT_DEFAULT_HOST: "smtp.gmail.com"
      EMAIL_TRANSPORT_DEFAULT_PORT: "587"
      EMAIL_TRANSPORT_DEFAULT_USERNAME: "no-reply@storvix.eu"
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: "Q*m69hVqm*gv"
      EMAIL_TRANSPORT_DEFAULT_TLS: "true"
    volumes:
      - /home/ubuntu/passbolt/gpg_volume:/etc/passbolt/gpg
      - /home/ubuntu/passbolt/jwt_volume:/etc/passbolt/jwt
      #- /mnt/docker/passbolt/gpg_volume:/etc/passbolt/gpg
      #- /mnt/docker/passbolt/jwt_volume:/etc/passbolt/jwt
    command: ["/usr/bin/wait-for.sh", "-t", "0", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 8099:80
        #- 9943:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433
